name = "github-webhook-worker"
main = "src/index.js"
compatibility_date = "2026-02-27"

[vars]
GITHUB_OWNER = "tlju"
GITHUB_REPO = "docker_image_pusher"
BRANCH = "main"
FILE_PATH = "images.txt"
GH_TOKEN = ""
WEBHOOK_SECRET = ""

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
